name = "assignment"
main = ".open-next/worker.js"
compatibility_date = "2025-12-05"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXT_PUBLIC_DJANGO_URL = "https://assignment-ov4q.onrender.com"